config/routes.rb
CollaboApp::Application.routes.draw do
  devise_for :users 
  resources :users
  resources :projects
  
  namespace :user do
    root :to => "users#home"
  end
  
  root :to => 'pages#home'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :content, :inspire_file_name
  
  # Paperclip method for attaching the file to the project
  has_attached_file :inspire
  
  # Projects belong to a user
  belongs_to :user
  
  # Validations
  validates :content, :presence => true, :length => { :maximum => 1000 }
  validates :user_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :location, :hobbies, :influences,
                  :inspiration, :password, :password_confirmation, :remember_me
  
  # Users have many projects that are associated with them
  has_many :projects, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # This is where we will define the static pages
  
  def home
    @title = 'Home'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  
  # The new action takes in new project data from the form in the view
  def new
    @project = Project.new
  end
  
  # The create action creates a new project through the current user
  def create
    @project = current_user.projects.build(params[:project])
    if @project.save
      flash[:notice] = "Project Created!"
      redirect_to projects_path
    else
      render root_path
    end
  end
  
  # The index action shows all the projects created by all users
  def index
    @projects = Project.all
    @title = "Projects"
  end
  
  # The edit action allows users to edit their projects by adding files or changing 
  # content or the name
  def edit
    @project = Project.find(params[:id])
  end
  
  # The update action updates the current project in the database
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project Updated!"
      redirect_to projects_path
    else
      render root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  # The home page is the redirect page after a successful login
  def home
    @title = "Home Base"
  end
  
  # The show page will show the user profile and show links to any projects that 
  # might be associated with the user
  def show
    @user = User.find(params[:id])
    @project = Project.new
    @projects = @user.projects
    @title = @user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Sets base title
  def title
    base_title = "Inspiration Depot"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  # Logo definition for abstraction from header
  def logo
    logo = image_tag("background.png", :alt => "background")
  end
  
  # Button definitions to include images in home page
  def button_up
    button_up = image_tag("buttonup.png", :alt => "buttonup")
  end
  
  def button_in
    button_in = image_tag("buttonin.png", :alt => "buttonin")
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<p><strong>&#169 Brainchild Development 2011</strong></p>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= image_tag('smalllogo.png', :alt => "smalllogo") %>
	<nav class="navheader">
	<ul>
		<li><%= link_to "Create New Project", new_project_path %></li>
		<li><%= link_to "View Projects", projects_path %></li>
		<li><%= link_to "Your Profile", user_path(current_user.id) %></li>
		<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
		<li><%= link_to "Sign Out", destroy_user_session_path %></li>
		<li><%= text_field_tag("Search", "Enter search terms here", 
								:size => 30) %></li>
	</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"</script>
		<![endif]-->
  		<%= stylesheet_link_tag 'collabo', :media => 'screen' %>
  		<%= javascript_include_tag :defaults %>
  		
	</head>
	<body>
		<div class="container">
			<% if user_signed_in? %>
				<%= render 'layouts/header' %>
			<% end %>
			<section class="round">
				<% flash.each do |name, msg| %>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				<% end %>
				<table class="main">
					<tr>
					<% if user_signed_in? %>
						<%= render 'shared/user_home' %>
					<% else %>
						<%= render 'shared/home' %>
					<% end %>
					</tr>
				</table>
			</section>
		</div>
		<div class="footer">
			<%= render :partial => 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/pages/home.html.erb
<p><b>Welcome to the Inspiration Depot Project</b>, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eros ipsum, tempus eu faucibus id, convallis vel justo. Proin consequat, leo sed hendrerit ultrices, mi libero mattis leo, eget mattis odio libero ac tortor. Nam eu dui vitae dolor mollis tempus non in ipsum. Fusce porta arcu sed enim rutrum in dignissim lorem elementum. Fusce at purus velit. Aliquam vitae tellus sed diam dapibus dignissim. Pellentesque vel orci erat. Nam lobortis pharetra quam ullamcorper volutpat. Quisque congue urna nec felis rutrum in placerat eros scelerisque. Donec id nisi lectus. Morbi vitae tortor at nisl auctor eleifend. Vivamus a felis purus, id porta nisi. Maecenas quis nibh eget arcu dignissim egestas et vel nisi. Sed sed dui urna, at molestie neque. Nunc euismod laoreet erat eu dapibus. Maecenas vulputate diam dapibus justo rhoncus in sollicitudin augue malesuada.</p><br />
	<div class="button"> 
		<h1><%= link_to button_in, new_user_session_path %></h1>
	</div>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<p><%= f.label :name %><br />
		<%= f.text_field :name %></p>
		<p><%= f.label :content %><br />
		<%= f.text_area :content %></p>
		<p><%= f.label :inspire_file_name %><br />
		<%= f.text_field :inspire_file_name %></p>
		<p><%= f.label :inspire_file %><br />
		<%= f.file_field :inspire %></p>
	</div>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/projects/index.html.erb
<div class="heading">
	<%= image_tag('projects.png', :alt => 'projects') %>
</div>
<% @projects.each do |project| %>
<table class="projects">
	<tr>
		<td>
			<ul>	
			<li><h2><b><%= project.name %></b></h2>
				<h3><i>by <% @id = project.user_id %>
						  <% @user = User.find(@id)%>
						  <%= @user.name %></i></h3></li>
			<li><b>Created on: </b><%= (project.created_at.to_formatted_s(
						:long_ordinal)).gsub! /\d\d\:\d\d/, '' %></li>
			<li><b>Content: </b><%= simple_format(project.content) %></li><br />
			<li><b>Attached Files: </b><%= project.inspire_file_name %></li><br />
			<li><%= link_to "Inspirational Files", project.inspire.url %></li><br />
			<% if current_user == @user %>
			<li><%= link_to "Edit", "projects/#{project.id}/edit" %></li>
			<li><%= link_to "Delete", project, :method => :delete,
			 						:confirm => "Are you sure?", 
									:title => "Delete #{project.name}" %></li><br />
			<% end %>
			</ul>
		</td>
	</tr>
</table>
<% end %>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<p><%= f.label :name %><br />
		<%= f.text_field :name %></p>
		<p><%= f.label :content %><br />
		<%= f.text_area :content %></p>
		<p><%= f.label :inspire_file_name %><br />
		<%= f.text_field :inspire_file_name %></p>
		<p><%= f.label :inspire_file %><br />
		<%= f.file_field :inspire %></p>
	</div>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(object.errors.count, "error") %>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
			from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_home.html.erb
<td><%= link_to logo, root_path %></td>
<td class="sidebar round">
	<%= render 'shared/links' %>
	<%= yield %>
</td>

app/views/shared/_user_home.html.erb
<td class="main">
	<%= yield %>
</td>

app/views/users/home.html.erb
<h1>Welcome <%= current_user.name %></h1><br />
<h2>About Inspration Depot</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel pretium nulla. Nam pulvinar, dui sit amet vestibulum aliquet, urna enim posuere est, et ullamcorper massa nulla a nunc. Fusce iaculis risus nec diam pulvinar vestibulum. Morbi dignissim feugiat varius. Donec sagittis hendrerit purus nec sagittis. Aliquam quis dolor leo. Etiam metus ipsum, ullamcorper eu varius a, vulputate id ligula. Pellentesque suscipit dolor id arcu consectetur quis consectetur dui accumsan. Donec nec massa a lorem vulputate faucibus. Suspendisse nibh erat, porttitor a aliquet ac, faucibus ac neque. Aliquam sit amet purus urna, in tempor dui. Mauris non sapien lectus, vel egestas tellus. Vestibulum tincidunt nulla sit amet erat porta molestie. Nulla est quam, laoreet quis fringilla eget, fermentum quis erat. Vestibulum eros odio, venenatis et tincidunt sollicitudin, fringilla eu libero. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum malesuada dui ut massa vestibulum vehicula. Fusce sagittis dui et lacus elementum eget rhoncus purus sagittis. Praesent diam elit, pellentesque id vulputate vel, fringilla non elit.</p><br />
<h2>Using Inspiration Depot</h2>
<p>Fusce nunc turpis, interdum nec placerat hendrerit, lobortis in velit. Donec ullamcorper dignissim ante id mattis. Sed molestie scelerisque odio, commodo tincidunt massa tempor ac. Morbi eget nibh vel odio mollis aliquam et ac sapien. Praesent tristique tellus sed leo aliquam id interdum mauris placerat. Mauris fringilla, risus fermentum posuere eleifend, ipsum neque porta ante, ac bibendum ipsum dolor vel turpis. Morbi sagittis metus vitae lorem scelerisque lobortis. Fusce accumsan nunc quis magna lobortis nec iaculis urna convallis. Integer sed lorem a sem feugiat posuere et at ipsum. Ut placerat, mi id elementum consequat, justo tortor sagittis quam, vulputate ultrices mauris enim eget est.</p>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
	<table class="profile round">
		<tr>
			<td><h2>Personal Information</h2><br />
				<ul>
					<li><b>Name: </b><%= @user.name %></li><br />
					<li><b>Email: </b><%= @user.email %></li><br />
					<li><b>Member Since: </b><%= (@user.created_at.to_formatted_s(
								:long_ordinal)).gsub! /\d\d\:\d\d/, '' %></li><br />
					<li><b>Location: </b><%= @user.location %></li><br />
					<li><b>Hobbies: </b><%= @user.hobbies %></li><br />
					<li><b>Artistic Influences: </b><%= @user.influences 
														%></li><br />
					<li><b>Inspired by: </b><%= @user.inspiration %></li><br />
				</ul>
			</td>
			<td><h2>Projects</h2><br />
				<% unless @projects.empty? %>
					<% @projects.each do |project| %>
						<ul>
							<li><%= project.name %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
								<%= (project.created_at.to_formatted_s(
								:long_ordinal)).gsub! /\d\d\:\d\d/, '' %></li><br />
						</ul>
					<% end %>
				<% end%>
			</td>
			<td><h2>Links</h2><br />
				<ul>
					<li><%= link_to "Facebook", "#" %></li><br />
					<li><%= link_to "Twitter", "#" %></li><br />
					<li><%= link_to "Website", "#" %></li><br />
					<li><%= link_to "Other", "#" %></li><br />
				</ul>
			</td>
		</tr>
	</table>